package com.SimonMk116.gendev.service.webwunderservice;

import com.SimonMk116.gendev.dto.SearchRequests;
import com.SimonMk116.gendev.service.webwunderservice.autogenerated.*;
import org.springframework.stereotype.Component;
import org.springframework.ws.client.core.support.WebServiceGatewaySupport;

@Component
public class WebWunderClient extends WebServiceGatewaySupport {

    public Output getInternetOffers(SearchRequests searchRequests) {
        // Prepare the request
        Address address = new Address();
        address.setStreet(searchRequests.getStreet());
        address.setHouseNumber(searchRequests.getHouseNumber());
        address.setCity(searchRequests.getCity());
        address.setPlz(searchRequests.getPlz());

        Input input = new Input();
        input.setAddress(address);
        input.setConnectionEnum(ConnectionType.DSL);
        input.setInstallation(true);

        LegacyGetInternetOffers request = new LegacyGetInternetOffers();
        request.setInput(input);

        return (Output) getWebServiceTemplate().marshalSendAndReceive(request);
    }
}

