package com.SimonMk116.gendev.service.webwunderservice;


import com.SimonMk116.gendev.dto.SearchRequests;
import com.SimonMk116.gendev.model.InternetOffer;
import com.SimonMk116.gendev.service.webwunderservice.autogenerated.Output;
import com.SimonMk116.gendev.service.webwunderservice.autogenerated.Product;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@Service
public class WebWunderService {

    private final WebWunderClient webWunderClient;

    @Autowired
    public WebWunderService(WebWunderClient client) {
        this.webWunderClient = client;
    }

    public Collection<InternetOffer> findOffers(String street, String houseNumber, String city, String plz) {
        SearchRequests request = new SearchRequests(street, houseNumber, city, plz);
        Output out = webWunderClient.getInternetOffers(request);

        List<Product> webWunderProducts = out.getProducts();
        Collection<InternetOffer> internetOffers = new ArrayList<>();

        for (Product product : webWunderProducts) {
            if (product.getProductInfo() == null ) {
                System.err.println("Warning: Product without productInfo (productID=" + product.getProductId() + ")");
            }
            InternetOffer offer = new InternetOffer(
                    product.getProductId(),
                    product.getProviderName(),
                    product.getProductInfo().getSpeed(),
                    product.getProductInfo().getMonthlyCostInCent(),
                    product.getProductInfo().getMonthlyCostInCentFrom25ThMonth()
            );
            internetOffers.add(offer);
        }
        System.out.println("Results Webwunder: " + internetOffers);

        return internetOffers;
    }
}
