
# fly.toml app configuration file generated for gendev-backend on 2025-05-31T21:43:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gendev-backend'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "20s" 
  interval = "15s"
  method = "GET"
  path = "/actuator/health/liveness" # Ensure this path is correct and your Actuator is enabled.
  timeout = "5s"
  protocol = "http"

[env]
  SPRING_PROFILES_ACTIVE = "production"
  LOG_LEVEL = "INFO"
  JAVA_OPTS = "-Xmx768m -Xms256m -XX:+UseG1GC"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
