# fly.toml app configuration file generated for gendev-backend on 2025-05-31T21:43:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gendev-backend"
primary_region = "fra" # Frankfurt, Germany - good choice for a central European location

kill_signal = "SIGTERM" # Use SIGTERM for a graceful shutdown
kill_timeout = 60       # Give your app up to 60 seconds to shut down gracefully

---

[build]
  dockerfile = "Dockerfile"

---

[deploy]
  strategy = "bluegreen"
  # release_command = "python manage.py migrate" # Example for Python/Django migrations
  # release_command = "./bin/rails db:migrate"    # Example for Ruby/Rails migrations
  # wait_timeout = "5m" # Default is 5m, increase if deploys time out often

---

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "info"

---

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true # Still useful if a machine stops unexpectedly or needs replacing
  auto_stop_machines = "off" # <--- IMPORTANT: Disable auto-stopping
  min_machines_running = 1   # <--- IMPORTANT: Ensure at least one machine is always running
  processes = [ "app" ]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [[http_service.checks]]
    grace_period = "15s"
    interval = "10s"
    method = "GET"
    path = "/healthz"
    timeout = "5s"
    protocol = "http"

---

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  processes = ["app"]
