# fly.toml app configuration file generated for gendev-backend on 2025-05-31T21:43:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gendev-backend"
primary_region = "fra" # Frankfurt, Germany - good choice for a central European location

kill_signal = "SIGTERM" # Use SIGTERM for a graceful shutdown
kill_timeout = 120       # Give your app up to 60 seconds to shut down gracefully


[build]
  dockerfile = "Dockerfile"


[deploy]
  strategy = "bluegreen"
  # For Spring Boot, migrations are often handled by Flyway/Liquibase on startup,
  # so a separate release_command not needed.
  # release_command = "java -jar /path/to/your/migration/tool.jar"
  wait_timeout = "5m"


[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "info"
  #general-purpose garbage collector.
  JAVA_OPTS = "-Xmx768m -Xms256m -XX:+UseG1GC"


[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off" # Disable auto-stopping
  min_machines_running = 1   # Ensure at least one machine is always running
  processes = [ "app" ]

  # Concurrency settings for load balancing and scaling.
  # "requests" is appropriate for HTTP-based Spring Boot services.
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200 # Adjust based on your Spring Boot app's capacity and thread pool
    hard_limit = 250 # Stop sending new requests at this limit

  [[http_service.checks]]
    grace_period = "45s" # Spring Boot start up
    interval = "10s" # How often Fly.io will check your app's health.
    method = "GET"
    path = "/actuator/health/liveness"
    timeout = "5s"
    protocol = "http"


[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  processes = ["app"]
