
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for absoluteVoucher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="absoluteVoucher">
 *   <complexContent>
 *     <extension base="{http://webwunder.gendev7.check24.fun/offerservice}voucher">
 *       <sequence>
 *         <element name="discountInCent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="minOrderValueInCent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "absoluteVoucher", propOrder = {
    "discountInCent",
    "minOrderValueInCent"
})
public class AbsoluteVoucher
    extends Voucher
{

    protected int discountInCent;
    protected int minOrderValueInCent;

    /**
     * Gets the value of the discountInCent property.
     * 
     */
    public int getDiscountInCent() {
        return discountInCent;
    }

    /**
     * Sets the value of the discountInCent property.
     * 
     */
    public void setDiscountInCent(int value) {
        this.discountInCent = value;
    }

    /**
     * Gets the value of the minOrderValueInCent property.
     * 
     */
    public int getMinOrderValueInCent() {
        return minOrderValueInCent;
    }

    /**
     * Sets the value of the minOrderValueInCent property.
     * 
     */
    public void setMinOrderValueInCent(int value) {
        this.minOrderValueInCent = value;
    }

}
