
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for connectionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="connectionType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="DSL"/>
 *     <enumeration value="CABLE"/>
 *     <enumeration value="FIBER"/>
 *     <enumeration value="MOBILE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "connectionType")
@XmlEnum
public enum ConnectionType {

    DSL,
    CABLE,
    FIBER,
    MOBILE;

    public String value() {
        return name();
    }

    public static ConnectionType fromValue(String v) {
        return valueOf(v);
    }

}
