
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for input complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="input">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="installation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="connectionEnum" type="{http://webwunder.gendev7.check24.fun/offerservice}connectionType"/>
 *         <element name="address" type="{http://webwunder.gendev7.check24.fun/offerservice}address"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "input", propOrder = {
    "installation",
    "connectionEnum",
    "address"
})
public class Input {

    protected boolean installation;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ConnectionType connectionEnum;
    @XmlElement(required = true)
    protected Address address;

    /**
     * Gets the value of the installation property.
     * 
     */
    public boolean isInstallation() {
        return installation;
    }

    /**
     * Sets the value of the installation property.
     * 
     */
    public void setInstallation(boolean value) {
        this.installation = value;
    }

    /**
     * Gets the value of the connectionEnum property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionType }
     *     
     */
    public ConnectionType getConnectionEnum() {
        return connectionEnum;
    }

    /**
     * Sets the value of the connectionEnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionType }
     *     
     */
    public void setConnectionEnum(ConnectionType value) {
        this.connectionEnum = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

}
