
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.SimonMk116.gendev.service.webwunderservice.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Input_QNAME = new QName("http://webwunder.gendev7.check24.fun/offerservice", "input");
    private static final QName _Product_QNAME = new QName("http://webwunder.gendev7.check24.fun/offerservice", "product");
    private static final QName _Output_QNAME = new QName("http://webwunder.gendev7.check24.fun/offerservice", "output");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.SimonMk116.gendev.service.webwunderservice.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Input }
     * 
     * @return
     *     the new instance of {@link Input }
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Product }
     * 
     * @return
     *     the new instance of {@link Product }
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Output }
     * 
     * @return
     *     the new instance of {@link Output }
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link LegacyGetInternetOffers }
     * 
     * @return
     *     the new instance of {@link LegacyGetInternetOffers }
     */
    public LegacyGetInternetOffers createLegacyGetInternetOffers() {
        return new LegacyGetInternetOffers();
    }

    /**
     * Create an instance of {@link Address }
     * 
     * @return
     *     the new instance of {@link Address }
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link PercentageVoucher }
     * 
     * @return
     *     the new instance of {@link PercentageVoucher }
     */
    public PercentageVoucher createPercentageVoucher() {
        return new PercentageVoucher();
    }

    /**
     * Create an instance of {@link AbsoluteVoucher }
     * 
     * @return
     *     the new instance of {@link AbsoluteVoucher }
     */
    public AbsoluteVoucher createAbsoluteVoucher() {
        return new AbsoluteVoucher();
    }

    /**
     * Create an instance of {@link ProductInfo }
     * 
     * @return
     *     the new instance of {@link ProductInfo }
     */
    public ProductInfo createProductInfo() {
        return new ProductInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Input }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Input }{@code >}
     */
    @XmlElementDecl(namespace = "http://webwunder.gendev7.check24.fun/offerservice", name = "input")
    public JAXBElement<Input> createInput(Input value) {
        return new JAXBElement<>(_Input_QNAME, Input.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Product }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Product }{@code >}
     */
    @XmlElementDecl(namespace = "http://webwunder.gendev7.check24.fun/offerservice", name = "product")
    public JAXBElement<Product> createProduct(Product value) {
        return new JAXBElement<>(_Product_QNAME, Product.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Output }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Output }{@code >}
     */
    @XmlElementDecl(namespace = "http://webwunder.gendev7.check24.fun/offerservice", name = "output")
    public JAXBElement<Output> createOutput(Output value) {
        return new JAXBElement<>(_Output_QNAME, Output.class, null, value);
    }

}
