@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://webwunder.gendev7.check24.fun/offerservice", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;
