
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for percentageVoucher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="percentageVoucher">
 *   <complexContent>
 *     <extension base="{http://webwunder.gendev7.check24.fun/offerservice}voucher">
 *       <sequence>
 *         <element name="percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="maxDiscountInCent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "percentageVoucher", namespace = "http://webwunder.gendev7.check24.fun/offerservice", propOrder = {
    "percentage",
    "maxDiscountInCent"
})
public class PercentageVoucher
    extends Voucher
{
    @XmlElement(namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected int percentage;
    @XmlElement(name = "maxDiscountInCent", namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected int maxDiscountInCent;

    /**
     * Gets the value of the percentage property.
     * 
     */
    public int getPercentage() {
        return percentage;
    }

    /**
     * Sets the value of the percentage property.
     * 
     */
    public void setPercentage(int value) {
        this.percentage = value;
    }

    /**
     * Gets the value of the maxDiscountInCent property.
     * 
     */
    public int getMaxDiscountInCent() {
        return maxDiscountInCent;
    }

    /**
     * Sets the value of the maxDiscountInCent property.
     * 
     */
    public void setMaxDiscountInCent(int value) {
        this.maxDiscountInCent = value;
    }

}
