
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="product">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="productId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="providerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productInfo" type="{http://webwunder.gendev7.check24.fun/offerservice}productInfo" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product", namespace = "http://webwunder.gendev7.check24.fun/offerservice", propOrder = {
    "productId",
    "providerName",
    "productInfo"
})
public class Product {

    @XmlElement(namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected int productId;
    @XmlElement(name = "providerName", namespace = "http://webwunder.gendev7.check24.fun/offerservice", required = true)
    protected String providerName;
    @XmlElement(name = "productInfo", namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected ProductInfo productInfo;

    /**
     * Gets the value of the productId property.
     * 
     */
    public int getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     */
    public void setProductId(int value) {
        this.productId = value;
    }

    /**
     * Gets the value of the providerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    /**
     * Gets the value of the productInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProductInfo }
     *     
     */
    public ProductInfo getProductInfo() {
        return productInfo;
    }

    /**
     * Sets the value of the productInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductInfo }
     *     
     */
    public void setProductInfo(ProductInfo value) {
        this.productInfo = value;
    }

}
