
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for productInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="productInfo">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="speed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="monthlyCostInCent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="monthlyCostInCentFrom25thMonth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="voucher" type="{http://webwunder.gendev7.check24.fun/offerservice}voucher" minOccurs="0"/>
 *         <element name="contractDurationInMonths" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="connectionType" type="{http://webwunder.gendev7.check24.fun/offerservice}connectionType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productInfo",namespace = "http://webwunder.gendev7.check24.fun/offerservice", propOrder = {
    "speed",
    "monthlyCostInCent",
    "monthlyCostInCentFrom25ThMonth",
    "voucher",
    "contractDurationInMonths",
    "connectionType"
})
public class ProductInfo {

    @XmlElement(namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected int speed;
    @XmlElement(namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected int monthlyCostInCent;
    @XmlElement(name = "monthlyCostInCentFrom25thMonth", namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected int monthlyCostInCentFrom25ThMonth;
    @XmlElement(namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected Voucher voucher;
    @XmlElement(namespace = "http://webwunder.gendev7.check24.fun/offerservice")
    protected int contractDurationInMonths;
    @XmlElement(name = "connectionType", namespace = "http://webwunder.gendev7.check24.fun/offerservice", required = true)
    @XmlSchemaType(name = "string")
    protected ConnectionType connectionType;

    /**
     * Gets the value of the speed property.
     * 
     */
    public int getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     */
    public void setSpeed(int value) {
        this.speed = value;
    }

    /**
     * Gets the value of the monthlyCostInCent property.
     * 
     */
    public int getMonthlyCostInCent() {
        return monthlyCostInCent;
    }

    /**
     * Sets the value of the monthlyCostInCent property.
     * 
     */
    public void setMonthlyCostInCent(int value) {
        this.monthlyCostInCent = value;
    }

    /**
     * Gets the value of the monthlyCostInCentFrom25ThMonth property.
     * 
     */
    public int getMonthlyCostInCentFrom25ThMonth() {
        return monthlyCostInCentFrom25ThMonth;
    }

    /**
     * Sets the value of the monthlyCostInCentFrom25ThMonth property.
     * 
     */
    public void setMonthlyCostInCentFrom25ThMonth(int value) {
        this.monthlyCostInCentFrom25ThMonth = value;
    }

    /**
     * Gets the value of the voucher property.
     * 
     * @return
     *     possible object is
     *     {@link Voucher }
     *     
     */
    public Voucher getVoucher() {
        return voucher;
    }

    /**
     * Sets the value of the voucher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Voucher }
     *     
     */
    public void setVoucher(Voucher value) {
        this.voucher = value;
    }

    /**
     * Gets the value of the contractDurationInMonths property.
     * 
     */
    public int getContractDurationInMonths() {
        return contractDurationInMonths;
    }

    /**
     * Sets the value of the contractDurationInMonths property.
     * 
     */
    public void setContractDurationInMonths(int value) {
        this.contractDurationInMonths = value;
    }

    /**
     * Gets the value of the connectionType property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionType }
     *     
     */
    public ConnectionType getConnectionType() {
        return connectionType;
    }

    /**
     * Sets the value of the connectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionType }
     *     
     */
    public void setConnectionType(ConnectionType value) {
        this.connectionType = value;
    }

}
