
package com.SimonMk116.gendev.service.webwunderservice.autogenerated;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for supportedCountry.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="supportedCountry">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="DE"/>
 *     <enumeration value="AT"/>
 *     <enumeration value="CH"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "supportedCountry")
@XmlEnum
public enum SupportedCountry {

    DE,
    AT,
    CH;

    public String value() {
        return name();
    }

    public static SupportedCountry fromValue(String v) {
        return valueOf(v);
    }

}
