package com.SimonMk116.gendev.config;

import com.SimonMk116.gendev.service.webwunderservice.WebWunderClient;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;
import org.springframework.ws.client.WebServiceClientException;
import org.springframework.ws.client.core.WebServiceTemplate;
import org.springframework.ws.client.support.interceptor.ClientInterceptor;
import org.springframework.ws.context.MessageContext;
import org.springframework.ws.transport.context.TransportContext;
import org.springframework.ws.transport.context.TransportContextHolder;
import org.springframework.ws.transport.http.HttpUrlConnection;

import java.io.IOException;
import java.net.URISyntaxException;


@Configuration
public class WebServiceConfig {

    @Bean
    public Jaxb2Marshaller marshaller() {
        Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
        marshaller.setContextPath("com.SimonMk116.gendev.service.webwunderservice.autogenerated");
        return marshaller;
    }

    @Bean
    public WebServiceTemplate webServiceTemplate(Jaxb2Marshaller marshaller) {
        WebServiceTemplate template = new WebServiceTemplate();
        template.setMarshaller(marshaller);
        template.setUnmarshaller(marshaller);
        template.setDefaultUri("https://webwunder.gendev7.check24.fun/endpunkte/soap/ws");
        // Add custom interceptor
        template.setInterceptors(new ClientInterceptor[]{
                new HttpHeaderInterceptor()});
        return template;
    }

    @Bean
    public WebWunderClient webWunderClient(WebServiceTemplate webserviceTemplate) {
        WebWunderClient client = new WebWunderClient();
        client.setWebServiceTemplate(webserviceTemplate);
        return client;
    }

    static class HttpHeaderInterceptor implements ClientInterceptor {
        //TODO: change from hard coded
        private final String API_KEY = "38A8D5853D7546C353A951CB6A9B421264B9969194E0BDB4D06604EAF5D5F8B1335CA2E9449CCA494E197589EBD9E3ED03C2A25348316CD817A18F062E2E4C51";

        @Override
        public boolean handleRequest(MessageContext messageContext) {
            try {
                TransportContext context = TransportContextHolder.getTransportContext();
                HttpUrlConnection connection = (HttpUrlConnection) context.getConnection();
                String uri = connection.getUri().toString();
                if (connection.getUri().toString().startsWith("https://webwunder.gendev7.check24.fun/")) {  //is api connection
                    connection.addRequestHeader("X-Api-Key", API_KEY);
                }
            } catch (IOException | URISyntaxException e) {
                throw new RuntimeException("Failed to add API key header",e);
            }
            return true;
        }

        @Override
        public boolean handleResponse(MessageContext messageContext) {
            return true;
        }

        @Override
        public boolean handleFault(MessageContext messageContext) {
            return true;
        }

        @Override
        public void afterCompletion(MessageContext messageContext, Exception e) throws WebServiceClientException {
        }
    }
}